server {
    listen 80;
    server_name kirito.fun www.kirito.fun;
    root /var/www/kirito;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /_next/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
